FROM php:7.1-cli

MAINTAINER sasan.rose@gmail.com

RUN apt-get update \
    && apt-get install zlib1g-dev \
    && pecl install redis-3.1.2 \
    && docker-php-ext-enable redis \
    && pecl install raphf-2.0.0 \
    && docker-php-ext-enable raphf \
    && pecl install propro-2.0.1 \
    && docker-php-ext-enable propro \
    && pecl install pecl_http-3.1.0 \
    && docker-php-ext-enable http \
    && docker-php-ext-install gettext
